--- 
:opac_uri: http://oasis.oregonstate.edu/record=%s
:item_container: .bibItemsEntry
:process_entry: 
- !ruby/regexp /\302\240/
- ""
:status_format: %3$s
:location_format: %1$s
:call_number_format : %2$s
:display_format: %3$s, %1$s
:availability: !ruby/regexp /^(AVAILABLE|INTERNET|LIB USE|NEW )/
