--- 
:opac_uri: http://oasis.oregonstate.edu/record=%s
:link_container: .bibLinks
:item_container: .bibItemsEntry
:process_entry: 
- !ruby/regexp /\302\240/
- ""
:result_fields:
  statusMessage: %3$s
  locationString: %1$s
  callNumber: %2$s
  displayString: %3$s, %1$s
:availability_test: 
  :source: %3$s
  :regexp: ^(AVAILABLE|INTERNET|LIB USE|NEW )
